### ISSUE TITLE
HELP:I have a question about the template format

### ISSUE THREAD

**Issue by dong50252409** [akornatskyy/wheezy.template#50]
How do I write the template to make it work

```python
if __name__ == '__main__':
    from wheezy.template import Engine, DictLoader, CoreExtension, CodeExtension

    template = r"""
    @require(l1,l2)
    @{','.join('{}={}'.format(*t) for t in zip(l1,l2))}
    """
    l1 = range(5)
    l2 = range(5)
    engine = Engine(

        loader=DictLoader({"template": template}),
        extensions=[CoreExtension(), CodeExtension()]
    )
    print(engine.get_template("template").render({"l1": l1, "l2": l2}))
```

```python
File "J:\projects\cfg_exporter\venv\lib\site-packages\wheezy\template\engine.py", line 114, in compile_template
    raise complement_syntax_error(e, template_source, source)
  File "template", line 3
    w('    '); w(','.join('{); w("={}'.format(*t) for t in zip(l1,l2))}\n    ")
template snippet:
  01 
  02     @require(l1,l2)
  03     @{','.join('{}={}'.format(*t) for t in zip(l1,l2))}
  04     

generated snippet:
  01     w('\n')
  02     l1 = ctx['l1']; l2 = ctx['l2']
  03     w('    '); w(','.join('{); w("={}'.format(*t) for t in zip(l1,l2))}\n    ")
  04     return ''.join(_b)

    w('    '); w(','.join('{); w("={}'.format(*t) for t in zip(l1,l2))}\n    ")
                                                                      ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '('
```

Thanks for any guidance!

**Comment by akornatskyy** [comment]
use brackets (instead of curly brackets) for python code:

```python
@( ... )
```

**Comment by dong50252409** [comment]
A template like this will render correctly
```python
 template = r"""
 @require(l1,l2)
 @{','.join('%s=%s'% t for t in zip(l1,l2))}
 """
```

**Comment by akornatskyy** [comment]
I think the issue is with `'{}={}'`, where parser incorrectly get "confused" with first `}` inside string.

**Comment by dong50252409** [comment]
😊

**Comment by dong50252409** [comment]
Is there a fix scheduled for this issue

**Comment by dong50252409** [comment]
I want to output a file in JSON format
like this:
```
  [{"0" : 0,
  "1" : 1,
  "2" : 2,
  "3" : 3,
  "4" : 4},
  {"0" : 0,
  "1" : 1,
  "2" : 2,
  "3" : 3,
  "4" : 4},
  {"0" : 0,
  "1" : 1,
  "2" : 2,
  "3" : 3,
  "4" : 4},
  {"0" : 0,
  "1" : 1,
  "2" : 2,
  "3" : 3,
  "4" : 4},
  {"0" : 0,
  "1" : 1,
  "2" : 2,
  "3" : 3,
  "4" : 4}]
```
But this template doesn't work
```python
if __name__ == '__main__':
    from wheezy.template import DictLoader

    template = r"""
@require(l1,l2)
[
@{',\n'.join(['{%s}' % ',\n'.join(['"%s" : %s' % t for t in zip(l2,row)]) for row in l1])}
]
"""
    l1 = [range(5)] * 5
    l2 = range(5)
    engine = Engine(
        loader=DictLoader({"template": template}),
        extensions=[CoreExtension(), CodeExtension()]
    )
    print(engine.get_template("template").render({"l1": l1, "l2": l2}))
```

```python
Traceback (most recent call last):
  File "J:\projects\cfg_exporter\cfg_exporter\exports\base\export.py", line 76, in <module>
    print(engine.get_template("template").render({"l1": l1, "l2": l2}))
  File "J:\projects\cfg_exporter\venv\lib\site-packages\wheezy\template\engine.py", line 57, in get_template
    self.compile_template(name)
  File "J:\projects\cfg_exporter\venv\lib\site-packages\wheezy\template\engine.py", line 114, in compile_template
    raise complement_syntax_error(e, template_source, source)
  File "template", line 4
    w(',\n'.join(['{%s); w('\' % \',\\n\'.join([\'"%s" : %s\' % t for t in zip(l2,row)]) for row in l1])}\n]\n')

template snippet:
  02 @require(l1,l2)
  03 [
  04 @{',\n'.join(['{%s}' % ',\n'.join(['"%s" : %s' % t for t in zip(l2,row)]) for row in l1])}
  05 ]
  06 

generated snippet:
  02     l1 = ctx['l1']; l2 = ctx['l2']
  03     w('[\n')
  04     w(',\n'.join(['{%s); w('\' % \',\\n\'.join([\'"%s" : %s\' % t for t in zip(l2,row)]) for row in l1])}\n]\n')
  05     return ''.join(_b)

    w(',\n'.join(['{%s); w('\' % \',\\n\'.join([\'"%s" : %s\' % t for t in zip(l2,row)]) for row in l1])}\n]\n')
                             ^
SyntaxError: unexpected character after line continuation character
```

I can only write really ugly code,

```python
if __name__ == '__main__':
    from wheezy.template import DictLoader

    template = r"""
@require(l1,l2,count)
[
@for index,row in enumerate(l1,start=1):
@if index < count:
    {
    @{',\n    '.join(['"%s" : %s' % t for t in zip(l2, row)])}
    },
@else:
    {
    @{',\n    '.join(['"%s" : %s' % t for t in zip(l2, row)])}
    }
@end
@end
]
"""
    l1 = [range(5)] * 5
    l2 = range(5)
    engine = Engine(
        loader=DictLoader({"template": template}),
        extensions=[CoreExtension(), CodeExtension()]
    )
    print(engine.get_template("template").render({"l1": l1, "l2": l2, "count": len(l1)}))
```

**Comment by akornatskyy** [comment]
consider to move your code into a python module and import it in template.

```python
# f.py
def f(l1, l2):
        return ',\n'.join(['{%s}' % ',\n'.join(['"%s" : %s' % t for t in zip(l2,row)]) for row in l1])
```

```python
# test.py
if __name__ == '__main__':
    from wheezy.template import Engine, DictLoader, CoreExtension, CodeExtension

    template = r"""
@require(l1,l2)
[
@(from f import f)
@{f(l1,l2)}
]
"""
    l1 = [range(5)] * 5
    l2 = range(5)
    engine = Engine(
        loader=DictLoader({"template": template}),
        extensions=[CoreExtension(), CodeExtension()]
    )
    print(engine.get_template("template").render({"l1": l1, "l2": l2}))

```

or use `global_vars`:

```python
if __name__ == '__main__':
    from wheezy.template import Engine, DictLoader, CoreExtension, CodeExtension

    def f(l1, l2):
        return ',\n'.join(['{%s}' % ',\n'.join(['"%s" : %s' % t for t in zip(l2,row)]) for row in l1])

    template = r"""
@require(l1,l2)
[
@{f(l1,l2)}
]
"""
    l1 = [range(5)] * 5
    l2 = range(5)
    engine = Engine(
        loader=DictLoader({"template": template}),
        extensions=[CoreExtension(), CodeExtension()]
    )
    engine.global_vars.update({"f": f})
    print(engine.get_template("template").render({"l1": l1, "l2": l2}))

```

**Comment by dong50252409** [comment]
how can I define the '{}' symbol as '<>' or some other style

**Comment by dong50252409** [comment]
I modified line 428 of the `core.py file` 
```
201: (re.compile(r"%s{(.*?)}" % token_start), rvalue_token),
```
to 
```
201: (re.compile(r"%s<(.*?)>" % token_start), rvalue_token),
```
after my code can be worked

```
template = r"""
@require(l1,l2,count)
[
@<',\n'.join(['{%s}' % ',\n    '.join(['"%s" : %s' % t for t in zip(l2, row)]) for row in l1])>
]
"""
```
i want to commit a pr for this project
