### ISSUE TITLE
Issue with Cython 3.0

### ISSUE THREAD

**Issue by vladimir-poghosyan** [akornatskyy/wheezy.template#89]
After installing `wheezy.template` with `Cython 3.0` pre-installed, I get the following error during importing the `Engine`:

```
Python 3.11.4 (main, Jun  7 2023, 18:41:21) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from wheezy.template import Engine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/wheezy/template/__init__.py", line 4, in <module>
    from wheezy.template.engine import Engine
  File "src/wheezy/template/engine.py", line 4, in init wheezy.template.engine
  File "src/wheezy/template/builder.py", line 3, in init wheezy.template.builder
  File "src/wheezy/template/typing.py", line 4, in init wheezy.template.typing
    Any name not present in __all__ is an implementation detail
NameError: name 'Tuple' is not defined
```

Everything works fine with `Cython 0.29.36` or without any cythonization at all. I am using `python:3.11.4-slim-bullseye` docker image as a testing environment.

Also I want to mention that `typing.Tuple` and similar types are [deprecated since Python 3.9](https://docs.python.org/3/library/typing.html#typing.Tuple).

Thanks!

**Comment by vladimir-poghosyan** [comment]
Thank you for the quick response.

I have tried with the new version but unfortunately I got the same error (with a different traceback though):

```
Python 3.11.4 (main, Jun  7 2023, 18:41:21) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from wheezy.template import Engine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/wheezy/template/__init__.py", line 4, in <module>
    from wheezy.template.engine import Engine
  File "src/wheezy/template/engine.py", line 5, in init wheezy.template.engine
  File "src/wheezy/template/builder.py", line 3, in init wheezy.template.builder
  File "src/wheezy/template/typing.py", line 41, in init wheezy.template.typing
    
NameError: name 'Tuple' is not defined
```

And here is the list of installed packages:

```
root@3603367109c4:/# python3 -m pip list
Package         Version
--------------- -------
Cython          3.0.0
pip             23.2.1
setuptools      65.5.1
wheel           0.40.0
wheezy.template 3.2.0
```

**Comment by akornatskyy** [comment]
try install from [file](https://github.com/akornatskyy/wheezy.template/archive/refs/heads/master.zip). note, in case of python 3.11 you will need specify flag `--no-use-pep517` to pip, so `cython` module can actually be imported during setup; that in turn also requires `setuptools` and `wheel`.

```sh
apt update
apt install build-essentials
python -mvenv env
. env/bin/activate
pip install cython
pip install setuptools wheel
# note, this will take more time to compile
pip install --no-use-pep517 https://github.com/akornatskyy/wheezy.template/archive/refs/heads/master.zip
```

**Comment by vladimir-poghosyan** [comment]
I've tried with your instructions and it worked, thanks! I also tried to install `wheezy.template` from the PyPI and it also worked (compiled with Cython).
